-- Criar sequence para ONGS
CREATE SEQUENCE SEQ_ONGS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Criar tabela ONGS
CREATE TABLE ONGS (
    ONG_ID NUMBER PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    DESCRICAO VARCHAR2(255),
    CNPJ VARCHAR2(18) NOT NULL UNIQUE,
    EMAIL VARCHAR2(100) NOT NULL,
    ENDERECO VARCHAR2(255)
);

-- Criar sequence para USUARIOS
CREATE SEQUENCE SEQ_USUARIOS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Criar tabela USUARIOS
CREATE TABLE USUARIOS (
    USUARIO_ID NUMBER PRIMARY KEY,
    APELIDO VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    SENHA VARCHAR2(100) NOT NULL,
    ROLE VARCHAR2(50) NOT NULL,
    ONG_ID NUMBER,
    CONSTRAINT FK_USUARIO_ONG FOREIGN KEY (ONG_ID) REFERENCES ONGS(ONG_ID)
);
