CREATE SEQUENCE SEQ_ONGS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE ONGS (
    ONG_ID INTEGER DEFAULT SEQ_ONGS.NEXTVAL NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    CNPJ VARCHAR2(18) NOT NULL,
    TELEFONE VARCHAR2(20),
    EMAIL VARCHAR2(100),
    DATA_FUNDACAO DATE,
    ENDERECO VARCHAR2(255),
    CONSTRAINT PK_ONGS PRIMARY KEY (ONG_ID)
);

ALTER TABLE USUARIOS
    ADD ROLE VARCHAR2(20);

ALTER TABLE USUARIOS
    ADD ONG_ID INTEGER;

ALTER TABLE USUARIOS
    ADD CONSTRAINT FK_USUARIOS_ONG
        FOREIGN KEY (ONG_ID)
            REFERENCES ONGS(ONG_ID);
